<?php
return array(
	"bodyBackground" => array(
		"value" => "#ffffff",
		"description" => __( "Body background", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"textColor" => array(
		"value"  => "#333333",
		"description" => __( "Text color", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"textEmboss" => array(
		"value"  => "#ffffff",
		"description" => __( "Text emboss", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"linkColor" => array(
		"value"  => "#3d6b99",
		"description" => __( "Link", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"linkColorHover" => array(
		"value"  => "#335980",
		"description" => __( "Link (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"baseFontFamily" => array(
		"value"  => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
		"description" => __( "Base font", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "font",
	),
	"baseFontSize" => array(
		"value"  => "13px",
		"description" => __( "Base font size", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "size",
	),
	"tableBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Table background", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"tableLabelBackground" => array(
		"value"  => "#f5f5f5",
		"description" => __( "Table header background", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"tableLabelText" => array(
		"value"  => "#9e9e9e",
		"description" => __( "Table header text", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"btnPrimaryBackground" => array(
		"value"  => "#6dbb4f",
		"description" => __( "Primary brand color", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Button background", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnBorder" => array(
		"value"  => "#cccccc",
		"description" => __( "Button border", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnTextColor" => array(
		"value"  => "#333333",
		"description" => __( "Button text", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"inputText" => array(
		"value"  => "#555",
		"description" => __( "Input field text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Input field background", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBorder" => array(
		"value"  => "#cccccc",
		"description" => __( "Input field border", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBorderFocus" => array(
		"value"  => "rgba(82,168,236,0.8)",
		"description" => __( "Input field border (focus)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputDisabledBackground" => array(
		"value"  => "#eeeeee",
		"description" => __( "Input field background (disabled)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"labelColor" => array(
		"value"  => "#aaaaaa",
		"description" => __( "Field label", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Dropdown list background", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownBorder" => array(
		"value"  => "rgba(0,0,0,0.15)",
		"description" => __( "Dropdown list border", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkColor" => array(
		"value"  => "#333333",
		"description" => __( "List item text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkColorHover" => array(
		"value"  => "#262626",
		"description" => __( "List item text (active/hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkBackgroundHover" => array(
		"value"  => "#f5f5f5",
		"description" => __( "List item background (active/hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"placeholderText" => array(
		"value" => "#999999",
		"description" => __( "Input field placeholder text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"todayColor" => array(
		"value"  => "#ffffdd",
		"description" => __( "Today color", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeGradientMiddle" => array(
		"value"  => "#3d6b99",
		"description" => __( "All-day badge color", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"eventImageShadow" => array(
		"value"  => "rgba(0,0,0,0.4)",
		"description" => __( "Event image shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"eventDefaultColor" => array(
		"value"  => "#3d6b99",
		"description" => __( "Event default color", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventDefaultColorHover" => array(
		"value"  => "#335980",
		"description" => __( "Event default color (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventStubAllDayText" => array(
		"value"  => "#ffffff",
		"description" => __( "All-day/multi-day event stub text", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventStubAllDayTextShadow" => array(
		"value"  => "rgba(0,0,0,0.4)",
		"description" => __( "All-day/multi-day event stub text shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventBorder" => array(
		"value"  => "#cccccc",
		"description" => __( "Event border", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Event background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventTimeBackground" => array(
		"value"  => "#eeeeee",
		"description" => __( "Event time background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventText" => array(
		"value"  => "#333333",
		"description" => __( "Event text", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"monthViewDateBackground" => array(
		"value"  => "#eaf4ff",
		"description" => __( "Month view date background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"dayViewNowMarkerColor" => array(
		"value"  => "#f2c539",
		"description" => __( "Week/day view now marker", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"agendaDateTitleBorder" => array(
		"value"  => "#6689AC",
		"description" => __( "Date label accent color", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateTitleBackground" => array(
		"value"  => "#ffffff",
		"description" => __( "Date label background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateBackground" => array(
		"value"  => "#f2f2f2",
		"description" => __( "Date background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaTodayBackground" => array(
		"value"  => "#f4f4bf",
		"description" => __( "Today background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
);
