<?php

/*
 * These are some default values that are installed in the options table
 * the first time.
 */
global $default_vals;
$default_vals = array( );

$default_vals['epl_help_url'] = 'http://www.wpeventsplanner.com/';
$default_vals['epl_help_email'] = 'help@wpeventsplanner.com';
$default_vals['epl_fields'] = array( '4e794a6eeeb9a' => Array( 'input_name' => '4e794a6eeeb9a', 'label' => 'Email', 'input_slug' => 'email', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '' ), 'epl_field_choice_value' => Array( '0' => '' ), 'description' => '', 'required' => 10, 'default_value' => '', 'validation' => 'email', 'epl_controller' => 'epl_form_manager', 'epl_system' => 1 ), '4e794a9a6b04f' => Array( 'input_name' => '4e794a9a6b04f', 'label' => 'First Name', 'input_slug' => 'first_name', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 10, 'default_value' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => 1 ), '4e794ab9c1731' => Array( 'input_name' => '4e794ab9c1731', 'label' => 'Last Name', 'input_slug' => 'last_name', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 10, 'default_value' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => 1 ), '4e794b4c6f26f' => Array( 'input_name' => '4e794b4c6f26f', 'label' => 'Address', 'input_slug' => 'address', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 0, 'default_value' => '', 'validation' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => '' ), '4e794b6ca7a75' => Array( 'input_name' => '4e794b6ca7a75', 'label' => 'City', 'input_slug' => 'city', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 0, 'default_value' => '', 'validation' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => '', ), '4e794bf90aecd' => Array( 'input_name' => '4e794bf90aecd', 'label' => 'State', 'input_slug' => 'state', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 0, 'default_value' => '', 'validation' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => '', ), '4e794c0522f8c' => Array( 'input_name' => '4e794c0522f8c', 'label' => 'Zip', 'input_slug' => 'zip', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 0, 'default_value' => '', 'validation' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => '', ), '4e794c113ea62' => Array( 'input_name' => '4e794c113ea62', 'label' => 'Phone', 'input_slug' => 'phone', 'input_type' => 'text', 'epl_field_choice_text' => Array( '0' => '', ), 'epl_field_choice_value' => Array( '0' => '', ), 'description' => '', 'required' => 0, 'default_value' => '', 'validation' => '', 'epl_controller' => 'epl_form_manager', 'epl_system' => '', ) );
$default_vals['epl_forms'] = array( '4e8b3920c839b' => Array( 'epl_form_id' => '4e8b3920c839b', 'epl_form_label' => 'Ticket Buyer', 'epl_form_slug' => 'ticket_buyer_information', 'epl_form_descritption' => 'Please give us your information', 'epl_form_options' => Array( '0' => 0, ), 'epl_controller' => 'epl_form_manager', 'epl_system' => 1, 'epl_form_fields' => Array( '0' => '4e794a9a6b04f', '1' => '4e794ab9c1731', '2' => '4e794a6eeeb9a', '3' => '4e794b4c6f26f', '4' => '4e794b6ca7a75', '5' => '4e794bf90aecd', '6' => '4e794c0522f8c', '7' => '4e794c113ea62' ) ) );
?>