<?php
return array(
	"bodyBackground" => array(
		"value" => "#000000",
		"description" => __( "Body background", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"textColor" => array(
		"value"  => "#b0b0b0",
		"description" => __( "Text color", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"textEmboss" => array(
		"value"  => "rgba(0,0,0,0)",
		"description" => __( "Text emboss", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"linkColor" => array(
		"value"  => "#5e8cba",
		"description" => __( "Link", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"linkColorHover" => array(
		"value"  => "#94b2d1",
		"description" => __( "Link (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "color",
	),
	"baseFontFamily" => array(
		"value"  => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
		"description" => __( "Base font", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "font",
	),
	"baseFontSize" => array(
		"value"  => "13px",
		"description" => __( "Base font size", AI1EC_PLUGIN_NAME ),
		"tab" => "general",
		"type" => "size",
	),
	"tableBackground" => array(
		"value"  => "#000000",
		"description" => __( "Table background", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"tableLabelBackground" => array(
		"value"  => "#303030",
		"description" => __( "Table header background", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"tableLabelText" => array(
		"value"  => "#6a6a6a",
		"description" => __( "Table header text", AI1EC_PLUGIN_NAME ),
		"tab" => "table",
		"type" => "color",
	),
	"btnPrimaryBackground" => array(
		"value"  => "#5e8cba",
		"description" => __( "Primary brand color", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnBackground" => array(
		"value"  => "#2b2b2b",
		"description" => __( "Button background", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnBorder" => array(
		"value"  => "#000000",
		"description" => __( "Button border", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"btnTextColor" => array(
		"value"  => "#b0b0b0",
		"description" => __( "Button text", AI1EC_PLUGIN_NAME ),
		"tab" => "buttons",
		"type" => "color",
	),
	"inputText" => array(
		"value"  => "#bbb",
		"description" => __( "Input field text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBackground" => array(
		"value"  => "#000000",
		"description" => __( "Input field background", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBorder" => array(
		"value"  => "#404040",
		"description" => __( "Input field border", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputBorderFocus" => array(
		"value"  => "rgba(82,168,236,0.8)",
		"description" => __( "Input field border (focus)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"inputDisabledBackground" => array(
		"value"  => "#303030",
		"description" => __( "Input field background (disabled)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"labelColor" => array(
		"value"  => "#999999",
		"description" => __( "Field label", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownBackground" => array(
		"value"  => "#000000",
		"description" => __( "Dropdown list background", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownBorder" => array(
		"value"  => "rgba(255,255,255,0.15)",
		"description" => __( "Dropdown list border", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkColor" => array(
		"value"  => "#999999",
		"description" => __( "List item text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkColorHover" => array(
		"value"  => "#dddddd",
		"description" => __( "List item text (active/hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"dropdownLinkBackgroundHover" => array(
		"value"  => "#003a66",
		"description" => __( "List item background (active/hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"placeholderText" => array(
		"value" => "#555",
		"description" => __( "Input field placeholder text", AI1EC_PLUGIN_NAME ),
		"tab" => "forms",
		"type" => "color",
	),
	"todayColor" => array(
		"value"  => "#002743",
		"description" => __( "Today color", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"alldayBadgeGradientMiddle" => array(
		"value"  => "#5e8cba",
		"description" => __( "All-day badge color", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"eventImageShadow" => array(
		"value"  => "rgba(0,0,0,0.3)",
		"description" => __( "Event image shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "calendar",
		"type" => "color",
	),
	"eventDefaultColor" => array(
		"value"  => "#5e8cba",
		"description" => __( "Event default color", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventDefaultColorHover" => array(
		"value"  => "#94b2d1",
		"description" => __( "Event default color (hover)", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventStubAllDayText" => array(
		"value"  => "#000000",
		"description" => __( "All-day/multi-day event stub text", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventStubAllDayTextShadow" => array(
		"value"  => "rgba(255,255,255,0.4)",
		"description" => __( "All-day/multi-day event stub text shadow", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventBorder" => array(
		"value"  => "#404040",
		"description" => __( "Event border", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventBackground" => array(
		"value"  => "#222222",
		"description" => __( "Event background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventTimeBackground" => array(
		"value"  => "#000000",
		"description" => __( "Event time background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"eventText" => array(
		"value"  => "#b0b0b0",
		"description" => __( "Event text", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"monthViewDateBackground" => array(
		"value"  => "#001829",
		"description" => __( "Month view date background", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"dayViewNowMarkerColor" => array(
		"value"  => "#f2c539",
		"description" => __( "Week/day view now marker", AI1EC_PLUGIN_NAME ),
		"tab" => "month",
		"type" => "color",
	),
	"agendaDateTitleBorder" => array(
		"value"  => "#35597d",
		"description" => __( "Date label accent color", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateTitleBackground" => array(
		"value"  => "#000000",
		"description" => __( "Date label background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaDateBackground" => array(
		"value"  => "#222222",
		"description" => __( "Date background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
	"agendaTodayBackground" => array(
		"value"  => "#040e16",
		"description" => __( "Today background", AI1EC_PLUGIN_NAME ),
		"tab" => "agenda",
		"type" => "color",
	),
);
